services:
  backend:
    image: ajinkya04/socketio-backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ajinkya04/socketio-frontend
    build: ./frontend
    ports:
      - "5173:5174"
    depends_on:
      - backend
    restart: always
